export default {
	SETTINGS_ICON: require('../../assets/images/settings.png'),
	FLASH_ICON: require('../../assets/images/flash.png'),
	SHOP_ICON: require('../../assets/images/shop.png'),
	FLASH_OFF_ICON: require('../../assets/images/noflash.png'),
	MICROPHONE_ICON: require('../../assets/images/microphone.png'),
	MICROPHONE_OFF_ICON: require('../../assets/images/nomicrophone.png'),
	CHECKBOX_OFF_ICON: require('../../assets/images/checkbox_off.png'),
	CHECKBOX_ICON: require('../../assets/images/checkbox.png'),
	LOGOUT_ICON: require('../../assets/images/logout.png'),
	LOGO_IMAGE: require('../../assets/images/logo.png'),
	MENU_ICON: require('../../assets/images/menu.png'),
	CART_ICON: require('../../assets/images/cart.png'),
	IMAGE_ICON: require('../../assets/images/image.png'),
	BUY_ICON: require('../../assets/images/buy.png'),
	INFO_ICON: require('../../assets/images/info.png'),
	PLACE_HOLDER_IMAGE: require('../../assets/images/placeHolder.png'),
	CLOSE_DARK_ICON: require('../../assets/images/close_dark_icon.png'),
	ADD_ICON: require('../../assets/images/add.png'),
	MINES_ICON: require('../../assets/images/mines.png'),
	REMOVE_ICON: require('../../assets/images/remove.png'),
}
